<?php
/* vim: set expandtab sw=4 ts=4 sts=4: */
/**
 * Manage logo display
 *
 * @package PhpMyAdmin-template
 *
 * @param bool   $displayLogo Display logo or not
 * @param bool   $useLogoLink Use link on logo or not
 * @param string $logoLink    Destination of link on logo
 * @param string $linkAttribs Link's attributes
 */
 
 require_once 'libraries/Scripts.class.php';
require_once 'libraries/RecentFavoriteTable.class.php';
require_once 'libraries/Menu.class.php';
require_once 'libraries/Console.class.php';
require_once 'libraries/navigation/Navigation.class.php';
require_once 'libraries/url_generating.lib.php';



$displayLogo = isset($displayLogo) ? $displayLogo : true;
$useLogoLink = isset($useLogoLink) ? $useLogoLink : false;
$logoLink = isset($logoLink) ? $logoLink : '#';
$linkAttribs = isset($linkAttribs) ? $linkAttribs : null;
if (!isset($logo)) {
    $logo = null;
    if (isset($GLOBALS['pmaThemeImage'])) {
        $imgTag = '<img src="' . $GLOBALS['pmaThemeImage'] . '%s" '
            . 'alt="phpMyAdmin" id="imgpmalogo" />';
        if (@file_exists($GLOBALS['pmaThemeImage'] . 'logo_left.png')) {
            $logo = sprintf($imgTag, 'logo_left.png');
        } elseif (@file_exists($GLOBALS['pmaThemeImage'] . 'pma_logo2.png')) {
            $logo = sprintf($imgTag, 'pma_logo2.png');
        }
    }
}
?>
  
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
 <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

 </head>
 
<!-- LOGO START -->
<?php if (false === $displayLogo) : ?>
    <!-- LOGO END -->
    <?php return; ?>
<?php endif; ?>
<div id="pmalogo">
    <?php if (true === $useLogoLink) : ?>
        <a href="<?php echo $logoLink; ?>"<?php echo isset($linkAttribs) ? ' ' . $linkAttribs : null; ?>>
    <?php endif; ?>
    <?php echo $logo; ?>
    <?php if (true === $useLogoLink) : ?>
        </a>
    <?php endif; ?>
<h1 style="font-size:36px;color:#1e406d;"> </h1>
</div>
<!-- LOGO END -->
