#!/bin/bash

# Integration test for RTM_Linux/check_RTM_Linux
# Should be run only on machines which do NOT have Nagios installed 
# and which do not have an enabled firewall.
cd sample-config
echo >> RTM_Linux.cfg # Hopefully this is a newline! I think RTM_Linux.cfg ends in a newling anyways.
echo 'command[check_test]=/tmp/check_yes.sh' >> RTM_Linux.cfg

# Make sure the directory exists such that RTM_Linux can create the RTM_Linux.pid file in the default location
mkdir /usr/ || true
mkdir /usr/local || true
mkdir /usr/local/rtm || true
mkdir /usr/local/rtm/var || true

# Make sure nagios user exists
useradd nagios

# Make a plugin
touch /tmp/check_yes.sh
echo 'echo OK' >> /tmp/check_yes.sh

# Give nagios control of plugins
chown nagios /tmp/check_yes.sh
chmod +x /tmp/check_yes.sh

# Start running the RTM_LINUX daemon to accept commands
cd ../src
./RTM_Linux -c ../sample-config/RTM_Linux.cfg -d

# Try to check_RTM_Linux with our check_test command/check_yes.sh plugin
./check_RTM_Linux -H 127.0.0.1 -c check_test

exit 0
